<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getAllAlbumsWithImages()
    {
        
        $resultSetMapping = new ResultSetMapping($this->getEntityManager());
        $resultSetMapping->addEntityResult('AppBundle\Entity\Album', 'a');
        $resultSetMapping->addFieldResult('a', 'id', 'id');
        $resultSetMapping->addFieldResult('a', 'name', 'name');
        $resultSetMapping->addJoinedEntityResult('AppBundle\Entity\Image', 'c', 'a', 'images');
        $resultSetMapping->addFieldResult('c', 'image_id', 'id');
        $resultSetMapping->addFieldResult('c', 'url', 'url');
        $resultSetMapping->addFieldResult('c', 'name', 'name');

        return $this->getEntityManager()->createNativeQuery("
            SELECT
              a.id,a.name,c.id as image_id,c.album_id,c.name,c.url
            FROM album a
              LEFT JOIN
              (
                SELECT i.*
                FROM image i
                WHERE
                  (
                    SELECT COUNT(*)
                    FROM image ii
                    WHERE i.album_id = ii.album_id AND
                          i.id <= ii.id
                  ) <= 5
              ) c ON a.id = c.album_id
        ", $resultSetMapping)->getResult();
    }
}
