Knp\Bundle\PaginatorBundle\Pagination\SlidingPagination:
    exclusion_policy: ALL
    virtual_properties:
        getPaginationData:
            groups: [album_page]
            serialized_name: data