AppBundle\Entity\Album:
    type: entity
    repositoryClass: AppBundle\Repository\AlbumRepository
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        name:
            type: string
            nullable: false
    oneToMany:
        images:
            targetEntity: AppBundle\Entity\Image
            mappedBy: album
            cascade:
                - all